<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBDQgxKx\Antidot_React_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBDQgxKx/Antidot_React_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBDQgxKx.legacy');

    return;
}

if (!\class_exists(Antidot_React_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBDQgxKx\Antidot_React_KernelDevDebugContainer::class, Antidot_React_KernelDevDebugContainer::class, false);
}

return new \ContainerBDQgxKx\Antidot_React_KernelDevDebugContainer([
    'container.build_hash' => 'BDQgxKx',
    'container.build_id' => 'ad452b6e',
    'container.build_time' => 1611345647,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBDQgxKx');
