<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require dirname(__DIR__, 3).'/vendor/autoload.php';
require __DIR__.'/ContainerBDQgxKx/Antidot_React_KernelDevDebugContainer.php';
require __DIR__.'/ContainerBDQgxKx/getDrift_FilesystemService.php';

$classes = [];
$classes[] = 'React\Filesystem\Filesystem';
$classes[] = 'React\EventLoop\LoopInterface';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

Preloader::preload($classes);
